[build-system]
requires = [
    "setuptools ~= 69.2.0;  python_version > '3.6'",
    "setuptools ~= 59.6;    python_version == '3.6'",
    "setuptools ~= 44.0;    python_version == '2.7'"
]
build-backend = "setuptools.build_meta"
